### ISSUE TITLE
백준 간단한 구현 문제 추천 입니다 ! 45도 배열 돌리기 문제

### ISSUE THREAD

**Issue by footdev** [SSAFY-09-D7/term1-group2#29]
[BOJ17276배열돌리기](https://www.acmicpc.net/problem/17276)

2차원 배열을 방향에 따라서 45도 돌려보는 문제입니다 ! 

인덱스 계산하는 문제 연습할 때 너무 쉽지도 어렵지도 않은 문제라 추천드려요 ~.~

**Comment by sseq007** [comment]
감사합니다!!

**Comment by sseq007** [comment]
함 풀어보겠슴돠~
